### ISSUE TITLE
Question consultation

### ISSUE THREAD

**Issue by yaolp123** [ambitious-octopus/MI-EEG-1D-CNN#25]
Dear authors: 
    Recently I  have looking your this project and feel interested in it !could have a dataset of this project?   Thanks a lot! I am looking forward to your reply Sincerely!

Best regards.

**Comment by ambitious-octopus** [comment]
This is the dataset: https://physionet.org/content/eegmmidb/1.0.0/

Please read the [README.md](https://github.com/ambitious-octopus/MI-EEG-1D-CNN/blob/master/README.md) on how to download and implement the network.
